name: Build FMOD Godot (Self-Hosted)

on:
  workflow_dispatch

env:
  FMOD_VERSION: 20212
  GODOT_ENGINE_VERSION: "4.0"
  GODOT_ENGINE_STAGE: "stable"
  INTEGRATION_VERSION: "1.0-alpha-1"

jobs:
  build-fmod:
    name: Windows FMOD Build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install dependencies (SCons, requests)
        run: python -m pip install scons requests

      - name: Download FMOD API
        run: |
          cd addons/FMOD/native/tools
          python download_fmod.py ${{ secrets.FMOD_USERNAME }} ${{ secrets.FMOD_PASSWORD }} api windows ${{ env.FMOD_VERSION }}
          7z x fmodstudioapi${{env.FMOD_VERSION}}win-installer.exe -o${{ github.workspace }}\addons\FMOD\native\fmodapi
          cd ../../../../

      - name: Compile Debug library
        shell: cmd
        run: |
          cd addons\FMOD\native
          scons platform=windows target=template_debug dev_build=yes generate_bindings=yes fmod_api=fmodapi -j6
          cd ..\..\..\

      - name: Compile Release library
        shell: cmd
        run: |
          cd addons\FMOD\native
          scons platform=windows target=template_release generate_bindings=yes fmod_api=fmodapi -j6
          cd ..\..\..\

      - name: Upload Build Output
        uses: actions/upload-artifact@v3
        with:
          name: windows-fmod-lib
          path: addons/FMOD/native/lib
